version: '3.8'

services:
  user-server:
    build:
      context: ./backend/user_server
    ports:
      - "8000:8000"
    volumes:
      - ./backend/user_server:/app
    env_file:
      - ./backend/user_server/.env
    depends_on:
      - db

  mail-server:
    build:
      context: ./backend/mail_server
    env_file:
      - ./backend/mail_server/.env
    ports:
      - "8001:8001"
    volumes:
      - ./backend/mail_server/app:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  db:
    build:
      context: ./backend/user_db
    env_file:
      - ./backend/user_db/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
