name: Create Jira Issue on GitHub Issue

on:
  issues:
    types: [opened]

jobs:
  create_jira_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create Jira Issue
        uses: atlassian/gajira-create@v3
        with:
          project: 'NVS'
          issuetype: 'Task'
          summary: '[WebApp] ${{ github.event.issue.title }}'
          description: |
            ${{ github.event.issue.body }}

            ---
            *Created from GitHub Issue:* ${{ github.event.issue.html_url }}
          fields: |
            {
              "parent": {
                "key": "NVS-57"
              }
            }