name: Deploy Play Server

on:
  push:
    branches: [ "53-feat-update-cicd-with-gitaction" ]
    paths:
      - 'backend/play_server/**'

jobs:
  deploy-play-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
            registry-type: public
        env:
            AWS_DEFAULT_REGION: us-east-1
            AWS_REGION: us-east-1

      - name: Build Docker image for play_server
        env:
          ECR_REGISTRY: public.ecr.aws/k8s0f8l3
          ECR_REPOSITORY_NAMESPACE: neves
          VERSION: ${{ github.sha }}
        run: |
          docker build --cache-from $ECR_REGISTRY/$ECR_REPOSITORY_NAMESPACE/play_server:$VERSION -t play-server-image -t $ECR_REGISTRY/$ECR_REPOSITORY_NAMESPACE/play_server:$VERSION -t $ECR_REGISTRY/$ECR_REPOSITORY_NAMESPACE/play_server:latest -f backend/play_server/Dockerfile backend/play_server

      - name: Run play_server container
        env:
          CLOUDFRONT_DOMAIN: ${{ secrets.CLOUDFRONT_DOMAIN }}
          CORS_ALLOWED_ORIGINS: ${{ secrets.CORS_ALLOWED_ORIGINS }}
          KEY_PAIR_ID: ${{ secrets.KEY_PAIR_ID }}
          S3_PRIVATE_KEY: ${{ secrets.S3_PRIVATE_KEY }}
        run: |
          docker run -d --name play-server-container \
            -p 8000:8000 \
            -e CLOUDFRONT_DOMAIN \
            -e CORS_ALLOWED_ORIGINS \
            -e KEY_PAIR_ID \
            -e S3_PRIVATE_KEY \
            play-server-image

      - name: Make test script executable
        run: chmod +x ./tests/play_server_test.sh

      - name: Run play_server test
        run: ./tests/play_server_test.sh

      - name: Display Docker logs
        if: always()
        run: docker logs play-server-container

      - name: Push Docker image to ECR
        if: success()
        env:
          ECR_REGISTRY: public.ecr.aws/k8s0f8l3
          ECR_REPOSITORY_NAMESPACE: neves
          VERSION: ${{ github.sha }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_NAMESPACE/play_server:$VERSION
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_NAMESPACE/play_server:latest