name: Deploy Play Server

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/play_server/**'

jobs:
  deploy-play-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
            registry-type: public
        env:
            AWS_DEFAULT_REGION: us-east-1
            AWS_REGION: us-east-1

      - name: Build and Push Docker image for play_server
        env:
          ECR_REGISTRY: public.ecr.aws/k8s0f8l3
          ECR_REPOSITORY_NAMESPACE: neves
          VERSION: ${{ github.sha }}
        run: |
          docker build --cache-from $ECR_REGISTRY/$ECR_REPOSITORY_NAMESPACE/play_server:$VERSION -t $ECR_REGISTRY/$ECR_REPOSITORY_NAMESPACE/play_server:$VERSION -t $ECR_REGISTRY/$ECR_REPOSITORY_NAMESPACE/play_server:latest -f backend/play_server/Dockerfile backend/play_server
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_NAMESPACE/play_server:$VERSION
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_NAMESPACE/play_server:latest
